### ISSUE TITLE
TO-DOs for backward process

### ISSUE THREAD

**Issue by shivendrra** [shivendrra/axgrad#13]
## Features to be added

- [x] `Axgrad`: autograd engine for computing gradients
- [x] Tensor.grad: fix the tensor class' grad & backward functions
- [x] `Module`: like pytorch's nn.Module
- [x] `Parameter` & `Embedding`: additional classes essential for neural networks
- [x] `Linear` & `Conv2d`: matrix methods for computation in neural networks
- [ ] #24
- [ ] Cmake support: python wrapper using cmake
- [ ] cuda support: parallelization using cuda library

## Problems

```python
a = [[2, 3, 5], [6, 4, 9]]
b = [[[1, 4, 6], [1, 5, 8]],
     [[1, 4, 6], [1, 5, 8]],
     [[1, 4, 6], [1, 5, 8]],
     [[1, 4, 6], [1, 5, 8]]]

from axon import tensor

a, b = tensor(a), tensor(b)
c = a + b
d = c.sum()
d.backward()
print(d)
print("d grad:", d.grad)
``` 
output: 
```powershell
Traceback (most recent call last):
  File "d:\Machine learning\ax-grad\test.py", line 14, in <module>
    d.backward()
  File "d:\Machine learning\ax-grad\axon\tensor.py", line 209, in backward
    node._backward()
  File "d:\Machine learning\ax-grad\axon\axgrad\functions\binary_ops.py", line 14, in __call__
    self.first.grad = self.backward(self.first.grad, self.out.grad)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Machine learning\ax-grad\axon\axgrad\functions\binary_ops.py", line 11, in backward
    return [self.backward(g, og) for g, og in zip(grad, out)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Machine learning\ax-grad\axon\axgrad\functions\binary_ops.py", line 11, in <listcomp>
    return [self.backward(g, og) for g, og in zip(grad, out)]
            ^^^^^^^^^^^^^^^^^^^^
  File "d:\Machine learning\ax-grad\axon\axgrad\functions\binary_ops.py", line 11, in backward
    return [self.backward(g, og) for g, og in zip(grad, out)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Machine learning\ax-grad\axon\axgrad\functions\binary_ops.py", line 11, in <listcomp>
    return [self.backward(g, og) for g, og in zip(grad, out)]
            ^^^^^^^^^^^^^^^^^^^^
  File "d:\Machine learning\ax-grad\axon\axgrad\functions\binary_ops.py", line 11, in backward
    return [self.backward(g, og) for g, og in zip(grad, out)]
                                              ^^^^^^^^^^^^^^
TypeError: 'int' object is not iterable
``` 

fixing this grad situation first, broadcasted tensor can't calculate gradients properly

**Comment by shivendrra** [comment]
almost everything is done, plus i dropped the idea for cmake
